### ISSUE TITLE
The example ""zipkin-brave-java-spring-boot-web"  still sends traces to Zipkin...

### ISSUE THREAD

**Issue by bsunders** [signalfx/tracing-examples#39]
I built the example as is and configured the ingest and token, but the spans apears to be sent to a default local zipkin server instead of to SignalFX:

 I/O error on POST request for "http://localhost:9411/api/v1/spans":

Application.properties: 
opentracing.reporter.signalfx.ingest_url=http://localhost:9080/v1/trace
(this is address of my Smart agent w/ trace listener enabled...

**Comment by adriancole** [comment]
also nothing made recently should be formatting v1 data!

**Comment by breedx-splk** [comment]
Outdated issue. Please reopen if still relevant.
