### ISSUE TITLE
environment name

### ISSUE THREAD

**Issue by aishvaryaps** [signalfx/tracing-examples#47]
How do I configure the environment name in lambda function from where the traces are coming..?
by default it takes unknown

I have a lambda function that reports to /v2/trace endpoint..(no smart gateway and no opentelemetry configured)

![image](https://user-images.githubusercontent.com/48279639/80339512-6c266800-887c-11ea-9d0f-53dab8142b75.png)

**Comment by aishvaryaps** [comment]
Hi ..
referring to : **tracing-examples/aws-lambda/jaeger-nodejs/index.js /**
How can I set environment name/cluster name ?
Just like we set service name

**Comment by breedx-splk** [comment]
Outdated issue. Please open a new issue in https://github.com/signalfx/splunk-otel-lambda if still relevant. Thank you for your understanding.
