### ISSUE TITLE
Update the Java OpenTelemetry examples to be more self-contained

### ISSUE THREAD

**Issue by jkwatson** [signalfx/tracing-examples#67]
ideas:

* provide a pre-configured docker-compose setup for the collector that will send data to Splunk ingest

**Comment by breedx-splk** [comment]
The java examples are being retired and we're pointing folks to the upstream examples...which does include collector via docker compose. 🤘🏻 https://github.com/open-telemetry/opentelemetry-java-examples/blob/2a27d4d46785e9dec08318493f9b8fbe3d423e6e/javaagent/docker-compose.yml
